### ISSUE TITLE
stupid dates

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#22]
@VictoriaStarnes 
1. Confirm dates are right for loggers that are read into R
2. missing values for intake?

![image](https://user-images.githubusercontent.com/654215/94708245-0007ce80-030a-11eb-9bb0-248fdcfe5ec3.png)

Missing 10:00
model_data[ year==2020&doy==26&hour%in%c(8,9,10),]
Missing 10:30
model_data[ year==2020&doy==40&hour%in%c(9,10,11),]
Missing 1:30 to 3:00
model_data[ year==2020&doy==68 &hour%in%c(0,1,2,3,4),]

![image](https://user-images.githubusercontent.com/654215/94705095-42c7a780-0306-11eb-8051-c39c22480a62.png)

**Comment by VictoriaStarnes** [comment]
1. Wrong origin start date in original date conversion.
2. Subset sections using as.Date() do not include time. Need to use as.POSIXct() in subset to pull date and time.
3. NaN's are at the beginning/end of logger profiles. Sometimes the first or last few logger recordings in a raw file only have a time recording, so I just delete these rows. I used na.approx() to fill in gaps. (15 values)

**Comment by mcolvin** [comment]
na.approx is throwing an error.

**Comment by VictoriaStarnes** [comment]
I FIXED IT!

The issue with na.approx was that it does not like trailing or leading NA values. Once those were removed that function ran fine. I then tried the model and it still wouldn't run. We had a gap on March 8th. After trying FOREVER to fill in that gap with NA values I realized that it was caused by daylight savings time. I then adjusted our continuous time to ignore springing forward. Then I was FINALLY able to run the model! It looks quite a bit better after the adjusted time and shifted start date.

![image](https://user-images.githubusercontent.com/45180904/94998653-136ca100-0579-11eb-8eea-7f4b73fddf9d.png)
